% Ama Hartman - AmaH@uw.edu

function fleetSize = calcFleetSize(wec, auv, energyStorage, maxFleetSize)
% calcFleetNum calculates the number of AUVs that can be supported by a
% single WEC with user-defined (or default) properties  
%
% INPUTS: 
% All generated by powerModel from user-inputs
% - wec: WEC object
% - auv: AUV object
% - energyStorage: EnergyStorage object
%
% OUTPUT: 
% - fleetSize: Number of AUVs that can be supported
% ------------------------------------------------------------------------


% Calculate power available after supporting WEC, assuming max WEC battery
powerValue = wec.meanPowerGen - wec.hotelLoad/(wec.n_battery^2); 

% Calculate MAX number of AUV's WEC could support in dock with given/calculated power generation
maxHotelFleet = floor((powerValue*energyStorage.n_battery*energyStorage.n_wecPwrTrnsfr - energyStorage.baseHotelLoad/energyStorage.n_battery/energyStorage.n_powerTransfer) / (auv.hotelLoad / energyStorage.n_battery / auv.n_battery / auv.n_powerTransfer + energyStorage.dockHotelLoad/energyStorage.n_battery/energyStorage.n_powerTransfer));  % PowerGen - wecHotelLoad - auvHotelLoad*fleetSize > 0    

% Time for an auv to go on mission + recharge + hotel during other auv mssn
cycleTime = auv.chargeTime(auv.mission) + auv.missionSpecs(auv.mission,2);  

% If no auv's can be supported on hotel, can not support any auvs
if maxHotelFleet < 1
    fleetSize = 0;

else 
    powAvailableFleet = floor((powerValue*energyStorage.n_battery*energyStorage.n_wecPwrTrnsfr - energyStorage.baseHotelLoad/energyStorage.n_battery/energyStorage.n_wecPwrTrnsfr)*cycleTime / (auv.chargeLoad/energyStorage.n_battery + energyStorage.dockHotelLoad*cycleTime/energyStorage.n_battery/energyStorage.n_powerTransfer));  % number of auv's that can recharge given the power available

    fleetSize = min(powAvailableFleet, maxHotelFleet);

    if maxHotelFleet >= 1 && powAvailableFleet < 1
        fleetSize = 1;
    end

    % fleetSize = maxHotelFleet;  % This produces rediculously large fleets, takes hours to run (and probably crashes matlab)

end

% Cap Fleet Size
if maxFleetSize ~= 0

    if fleetSize > maxFleetSize
        fleetSize = maxFleetSize;

    end
end
        
end

