% simulateSystemOperations steps through each timestep for the given simulation, 
% calculates battery levels of the WEC and all AUVs in its assigned fleet,
% and generates an operational state schedule for the AUV(s). 
%
% Inputs: 
% All generated by powerModel from user-inputs
% - simTime: [h] Time series for simulation 
% - simResults: SimResults object
% - auvFleet: (1xm) array of m AUV objects
% - energyStorage: EnergyStorage object
% - incorpStagger: Flag to (1) stagger AUV deployments, or (0) not
%
% Outputs: 
% - eStorageBatteryLvl: [Wh] (nx1) time series of central battery level
% - wecBatteryLvl: [Wh] (nxm) time series of WEC battery level(s) with m
%   corresponding to each wec in wecFleet
% - auvBatteryLvl: [Wh] (nxm) time series of AUV battery level(s) with m
%   corresponding to each auv in auvFleet
% - auvSchedule: time series of AUV operational state schedule with 1)
%   Executing AUV mission, 2) Recharging, 3) Docked and fully charged
%
% Ama Hartman - 2026


function [eStorageBatteryLvl, wecBatteryLvl, auvBatteryLvl, auvSchedule] = simulateSystemOps(simTime, simResults, auvFleet, energyStorage, incorpStagger)

%% Pre-Timestep Calculations
dt = simTime(2) - simTime(1); 

auvBatteryLvl = zeros(length(simTime), length(auvFleet)); 
wecBatteryLvl = zeros(length(simTime)+1, length(simResults.wecFleet)); 
wecBatteryLvl(1,:) = [simResults.wecFleet.batteryCapacity];  % initialize at full-charge
eStorageBatteryLvl = zeros(length(simTime)+1, 1);
eStorageBatteryLvl(1) = min(auvFleet(1).chargeLoad*length(auvFleet)/energyStorage.n_battery + auvFleet(1).chargeTime*energyStorage.hotelLoad/energyStorage.n_battery/energyStorage.n_powerTrnsfr - ( (simResults.lowPowerGen-simResults.aggWECHotelLoad)*auvFleet(1).chargeTime*energyStorage.n_battery*energyStorage.n_wecPwrTrnsfr ), energyStorage.batteryCapacity);% *1.05;  % Given lowest possible power generation during recharge OR 5% of WEC battery, if threshold is negative (i.e. if power gen > power draw)
if eStorageBatteryLvl(1) < 0.25*energyStorage.batteryCapacity
    eStorageBatteryLvl(1) = 0.85*energyStorage.batteryCapacity;  % Initialize at 85% max charge if power generated is > max power draw. Matches EnergyStorage.reset()'s default initialization.
end
auvSchedule = zeros(length(simTime), length(auvFleet)); 


% Initialize AUV deployment stagger values
if incorpStagger == 1
    staggerHours = min( ([auvFleet.missionTime]+[auvFleet.chargeTime]) ./ length(auvFleet) );  % min should still yield the desired 'mean' for homogenous fleets...
    simTimeLastDeployment = -staggerHours; 
else
    staggerHours = 0;
    simTimeLastDeployment = 0;
end

% Precomputed wec fleet values
wecBatteryCapacity = [simResults.wecFleet.batteryCapacity];
wecBatteryEfficiency = [simResults.wecFleet.n_battery];
wecHotelDraw = [simResults.wecFleet.hotelLoad]./ (wecBatteryEfficiency.^2);
wecPowerGenMat = [simResults.wecFleet.powerGenMeans];

%% Run timestep calculations
for i = 1:length(simTime)  

    %% WEC Battery & Power Gen Overflow
    % Calculate WEC battery level for next iteration & amount of power
    % generated for central battery storage
        
    wecBatteryLvl(i+1, :) = min(wecBatteryLvl(i, :) + (-wecHotelDraw + wecPowerGenMat(i, :).*wecBatteryEfficiency)*dt, wecBatteryCapacity);
    for w = 1:numel(simResults.wecFleet)
        simResults.wecFleet(w).battery = wecBatteryLvl(i, w);  % Could maybe phase out
    end
    pGenToWEC = sum(([simResults.wecFleet.batteryCapacity] - wecBatteryLvl(i,:)) ./ (dt * [simResults.wecFleet.n_battery])) + (simResults.aggWECHotelLoad);

    % Calculate power overflow (to central storage)
    if pGenToWEC < simResults.powerGenMeans(i)  
        extraPower = simResults.powerGenMeans(i) - pGenToWEC;
   
    else  % All power generated goes to WEC
        extraPower = 0;  

    end

    % if wecBatteryLvl(i+1) < wec.lowBatteryLvl
    if any(wecBatteryLvl(i+1,:) < [simResults.wecFleet.lowBatteryLvl])
        warning('Low WEC battery. Need to implement WEC energy draw from central storage.')
    end


    %% Extract current auv operational states for calculations
    auvOpStates = [auvFleet.opState];
    auvOpStates = auvOpStates(1:2:end);  % collect current operational state, not time associated with it

    
    %% Central storage battery
    % Calculate energy storage battery level for next iteration using avg
    % power and opState(s) at current simTime
    
    % If >= 100% charged, dumps extra power and keeps battery at max
    eStorageBatteryLvl(i+1) =      min(eStorageBatteryLvl(i) + (extraPower*energyStorage.n_wecPwrTrnsfr*energyStorage.n_battery + - energyStorage.hotelLoad/energyStorage.n_battery/energyStorage.n_powerTrnsfr - sum([auvFleet.wecBatteryDraw])/energyStorage.n_battery )*dt, energyStorage.batteryCapacity);  % [prev.battery + (draws & gains)*dt]
    eStorageLowBatteryFlag = 0;
    
    % If central battery is low, stop charging AUVs but still supply hotel loads
    if eStorageBatteryLvl(i+1) < energyStorage.lowBatteryLvl
        eStorageLowBatteryFlag = 1;
        eStorageBatteryLvl(i+1) =  min(eStorageBatteryLvl(i) + (extraPower*energyStorage.n_wecPwrTrnsfr*energyStorage.n_battery + - energyStorage.hotelLoad/energyStorage.n_battery/energyStorage.n_powerTrnsfr - sum( (auvOpStates == 3 | auvOpStates == 2) .* [auvFleet.hotelLoad] ./ [auvFleet.n_powerTransfer] ./ [auvFleet.n_battery]) /energyStorage.n_battery )*dt, energyStorage.batteryCapacity);  % [prev.battery + (draws & gains)*dt]
    end

    % Save current battery level in energy storage object (for battery estimation calcs)
    energyStorage.battery = eStorageBatteryLvl(i+1);  

    
    %% AUV Battery
    % Calculate and save AUV battery level(s)
    for j = 1:length(auvFleet)
        auvFleet(j).calcBatteryLvl(simTime(i));
        auvBatteryLvl(i, j) = auvFleet(j).battery(2);  % Extract current battery lvl
    end
    

    %% AUV Operational State
    % Evaluate opState of AUV(s) & change as applicable for next timestep

    % Save current timestep operational states (calculated at the end of
    % last timestep)
    for p = 1:length(auvFleet)
        auvSchedule(i, p) = auvFleet(p).opState(1); 
    end

    if i < length(simTime)
    
        % If central storage goes into battery-save mode, stop charging AUV(s)
        if eStorageLowBatteryFlag == 1
            indxCharging = find(auvOpStates == 2);
            if any(indxCharging)
                for k = 1:length(indxCharging)
                    auvFleet(indxCharging(k)).changeOpState(3, simTime(i+1));
                end
            end
    
        else  % start charging auv's docked and still below max battery
            indxNeedCharge = find(logical( (auvOpStates == 3) .* (auvBatteryLvl(i,:) < [auvFleet.batteryCapacity]) ));   
            if any(indxNeedCharge)
                for l = 1:length(indxNeedCharge)
                    auvFleet(indxNeedCharge(l)).changeOpState(2, simTime(i+1));
                end
            end
    
        end
    
        % Deployed AUV completes mission & returns
        onMissionLogic = (auvOpStates == 1);
        indxMissionComplete = find(logical( onMissionLogic .* ([auvFleet.opTimeComplete] <= simTime(i+1)) ));
        if any(indxMissionComplete)
            for m = 1:length(indxMissionComplete)
                auvFleet(indxMissionComplete(m)).changeOpState(2, simTime(i+1));
            end
        end
    
        % Charging AUV finishes charging: 
        indxChargingComplete = find(logical( (auvOpStates == 2) .* ([auvFleet.opTimeComplete] <= simTime(i+1)) ));
        if any(indxChargingComplete)
            for n = 1:length(indxChargingComplete)
                auvFleet(indxChargingComplete(n)).changeOpState(3, simTime(i+1));
            end
        end
    
        % For docked AUV to leave: 
        % - AUV must have enough battery for the mission
        % - Central battery must have enough power to fully recharge AUV when it returns
        % tempMissionBattUsed = arrayfun(@(auv) auv.missionBattPrcnt, auvFleet);
        tempMissionBattUsed = zeros(1, length(auvFleet));
        for o = 1:length(auvFleet)
            tempMissionBattUsed(o) = auvFleet(o).missionBattPrcnt; 
        end
        auvReadyToDeploy = (auvOpStates ~= 1) .* (auvBatteryLvl(i,:) >= (([auvFleet.rechargeThreshold] + tempMissionBattUsed) .* [auvFleet.batteryCapacity]) ); % cellfun(@(auv) (auv.rechargeThreshold + auv.missionBattPrcnt) * auv.batteryCapacity, auvFleet) );  
        if any(auvReadyToDeploy ~= 0) && (simTime(i+1) > simTimeLastDeployment+staggerHours)
        % if any(auvReadyToDeploy ~= 0) 
            nonzroindx = find(auvReadyToDeploy); 
            auvToDeploy = nonzroindx(1);  % Deploy first AUV available
    
            [eStorageFutureBattery, eStorageNoBatteryFlag] = energyStorage.estBattery(auvFleet, simTime(i+1), dt, auvToDeploy, simResults);
                
            % If estimated battery is above 0, and the central battery is not expected to drop below 0, send auv on mission
            if (eStorageFutureBattery > 0) && (eStorageNoBatteryFlag == 0) 
                auvFleet(auvToDeploy).changeOpState(1, simTime(i+1)); 
                simTimeLastDeployment = simTime(i+1);
                
            end
        end
    end


end  % timesteps

% Save battery levels for simulation domain
wecBatteryLvl = wecBatteryLvl(1:end-1, :); 
eStorageBatteryLvl = eStorageBatteryLvl(1:end-1); 

end